#+BEGIN_EXPORT html
---
title: 癌症
author: Felix Chang
tags:
    - 異化
    - 體制化
    - 療癒
    - 癌症
---
#+END_EXPORT

#+BEGIN_EXPORT html
癌症是經年累月生活方式不正確導致的結果。 ...... 岡本裕，《90% 的醫生都誤解癌症》
#+END_EXPORT

兩年前，當我看到 103 年度各年齡層三大死因死，忍不住嚇了一跳，我沒有想到癌症已經在大於 25 歲的各個族群裡，成為死亡比例最高的一種疾病，而且，最不可思議的是，50-60 歲這個年齡的人死於癌症的「比例」，比任何年齡層還都要高。

- 下圖是 103 年度的圖表。
<blockquote class="imgur-embed-pub" lang="en" data-id="a/CJfdN"><a href="//imgur.com/CJfdN">台灣103年，死因統計</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

- 下圖是 105 年度的圖表。
<blockquote class="imgur-embed-pub" lang="en" data-id="lVmBvbA"><a href="//imgur.com/lVmBvbA"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

上面這兩張圖，是由從事保險的朋友提供給我的[fn:1]，我們可以稍稍的比較兩者的差別。


如果癌症只是一種老化的現象，那麼，何以更高年齡的人卻沒有發現相對應的比例？或許有人會說，因為許多老年人在死於癌症前，就已經死於心血管等等的疾病，但這個理由實在過於牽強，因為基於這個理由，其實癌症並不是那麼嚴重，也不是什麼需要馬上處理的疾病，但現實上似乎不是如此。

那麼，是因為環境污染嗎？我絕對相信環境污染是極為重要的致癌因子，但我也感到不太能理解，因為更高年齡的人接受了更長時間的污染，為何沒有表現在數據上？有兩個激進的解答，第一，這年年紀更大的人，他們在環境污染前，也就是年幼之時，得到了重要的滋養。第二，他們因為沒有現代醫學支援，卻在「天擇」之下而活下來的人，所以他們天生就比較強壯。

我實在無法認同這兩個說法，在這兩個說法面前，人實在對於自己的健康，特別是年紀愈大的人，就愈加無能為力了。我認為這和人們「面臨退休」有著極為重要的相關性，特別是在和病友們接觸過後，這個想法更是占領了我的思緒。

# 體制化

我第一次聽到這個名詞，是在《刺激1995》

那時，有幾個朋友和我接觸，因為他們幾乎都身陷憂鬱，而無法自拔，我在和他們幾次對談後，發現他們的生命，幾乎已經陷社會的體制化而無法自拔，他們年輕時就進了職校，因為學校和企業合作的關系，一畢業他們就順利的進到企業中去工作，而工作的內容，就是許多機械化的重復動作，他們是一線的作業員，日復一日的重復著同樣單調的工作。

他們的心思單純，但在面對困難時，貧乏的資源和知識，使的連和他們對談都呈現困難，他們無法深刻的理解生命的豐富與美好，因為所有的辭彙和想像，對他們來說，都是遙不可以甚至是難以想像的東西。

這個現象，我也在 50-60 歲的人身上看到了，除了賺錢外，他們對生活，沒有辦法有太多的想像，宗教提供了一個出口，但萬一找不到那個適合的宗教呢？

抱著這個疑惑，我不斷的前進，我受到的打擊也愈大，當我和患者一起找到生命中最熱愛的事物時，現實撲滅了一切，人們找不到可以創作的舞台。我感到深深的痛苦。這也讓我開始意識到，要幫助病人走出眼前的難關，社會得負更多的責任。

偶然之中，我看到了馬克斯的著作，他的言論，如同當頭棒喝，首先，他說，

# Footnotes

* Footnotes

[fn:1] 離開學術界才發現，圖表的製作是一門藝術，第一個要求是，必須要做到通俗易懂。
